// @ts-ignore
import type { Config } from 'tailwindcss'
const config: Config = {
  content: ['./src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        // Stitch Design System — Wild West / Neon Frontier palette
        'primary': '#ffb4ac',
        'on-primary': '#690007',
        'primary-container': '#d72b2b',
        'on-primary-container': '#fff3f2',
        'primary-fixed': '#ffdad6',
        'primary-fixed-dim': '#ffb4ac',
        'inverse-primary': '#bc131b',

        'secondary': '#ffd65b',
        'on-secondary': '#3d2f00',
        'secondary-container': '#e7b900',
        'on-secondary-container': '#5f4a00',
        'secondary-fixed': '#ffe08b',
        'secondary-fixed-dim': '#f0c110',

        'tertiary': '#ffb59b',
        'on-tertiary': '#5b1a00',
        'tertiary-container': '#b15734',
        'on-tertiary-container': '#fff4f1',

        'surface': '#131313',
        'surface-dim': '#131313',
        'surface-bright': '#3a3939',
        'surface-container-lowest': '#0e0e0e',
        'surface-container-low': '#1c1b1b',
        'surface-container': '#201f1f',
        'surface-container-high': '#2a2a2a',
        'surface-container-highest': '#353534',
        'surface-brown': '#1C1410',
        'surface-variant': '#353534',
        'charcoal-muted': '#2A2420',

        'on-surface': '#e5e2e1',
        'on-surface-variant': '#e5bdb9',
        'inverse-surface': '#e5e2e1',
        'inverse-on-surface': '#313030',

        'background': '#131313',
        'on-background': '#e5e2e1',

        'outline': '#ac8885',
        'outline-variant': '#5c403d',
        'surface-tint': '#ffb4ac',

        'error': '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',

        'paper-white': '#F5F0E8',
        'ember-glow': 'rgba(215, 43, 43, 0.15)',

        // Legacy aliases (backward compat)
        'wild-red': '#D72B2B',
        'wild-red-light': '#ffb4ac',
        'wild-red-dark': '#93000e',
        'wild-yellow': '#ffd65b',
        'wild-yellow-dark': '#e7b900',
        'wild-black': '#131313',
        'wild-black-light': '#1c1b1b',
        'wild-brown': '#1C1410',
        'wild-brown-light': '#2A2420',
        'wild-charcoal': '#2a2a2a',
        'wild-paper': '#F5F0E8',
        'wild-rust': '#8B3A1A',
        'wild-ember': 'rgba(215, 43, 43, 0.15)',
        'muncherz-red': '#D62828',
        'muncherz-yellow': '#F7B731',
        'muncherz-black': '#0A0A0A',
        'muncherz-white': '#FAFAFA',
        'success': '#22C55E',
        'warning': '#F59E0B',
        'error-legacy': '#EF4444',
        'info': '#3B82F6',
      },
      fontFamily: {
        'display': ['DM Sans', 'sans-serif'],
        'body': ['Inter', 'sans-serif'],
        'mono': ['JetBrains Mono', 'monospace'],
        'display-lg': ['DM Sans', 'sans-serif'],
        'headline-md': ['DM Sans', 'sans-serif'],
        'section-label': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
        'price-tag': ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'display-lg': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'section-label': ['14px', { lineHeight: '20px', letterSpacing: '0.1em', fontWeight: '800' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'price-tag': ['18px', { lineHeight: '18px', fontWeight: '700' }],
      },
      borderRadius: {
        'wild-sm': '0.25rem',
        'wild-default': '0.5rem',
        'wild-md': '0.75rem',
        'wild-lg': '1rem',
        'wild-xl': '1.5rem',
        'wild-card': '12px',
        'wild-sheet': '24px',
        'wild-button': '8px',
        'wild-pill': '9999px',
        'sm': '0.25rem',
        'DEFAULT': '0.5rem',
        'lg': '0.75rem',
        'xl': '1rem',
        '2xl': '1.5rem',
        'full': '9999px',
      },
      spacing: {
        'stack-sm': '8px',
        'stack-md': '16px',
        'stack-lg': '32px',
        'margin-mobile': '20px',
        'gutter': '16px',
        'base': '4px',
      },
      boxShadow: {
        'wild-glow': '0 0 20px rgba(215, 43, 43, 0.3)',
        'wild-ember': '0 4px 20px rgba(215, 43, 43, 0.15)',
        'ember': '0 0 20px rgba(215, 43, 43, 0.2)',
        'ember-heavy': '0 0 30px rgba(215, 43, 43, 0.4)',
      },
    },
  },
  plugins: [],
}
export default config